fix: remove download dependency from `manta-benchmark`
Manta-Network/manta-rs pull request #103
Opened 2022-06-16 22:01 UTC by BoyuanFeng

## Summary

Fix compatibility issue between `manta-benchmark` and `manta-parameters/download`.

## Details

`openssl` is not well-supported yet in `wasm`. `manta-parameters` use `openssl` to download lfs files while `manta-benchmark` contains `wasm` benchmarks. Currently, `manta-benchmark` implicitly imports `openssl` through `manta-pay/test` which imports `manta-parameters/download`.

In this PR, we separate the feature `manta-parameters/download` from `manta-pay/test` to avoid this implicit import of `openssl` in `manta-benchmark`.

Issue: #104 

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [x] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [x] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [x] Re-reviewed `Files changed` in the GitHub PR explorer.
- [x] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2022-06-16 22:09 UTC, tsunrise approved these changes

2022-06-16 22:44 UTC, bhgomes requested changes

2022-06-16 22:44 UTC, bhgomes commented on manta-pay/Cargo.toml
> +manta-pay = { path = ".", default-features = false, features = ["download", "groth16", "scale", "scale-std", "std", "test"] }
Why not just import `manta-parameters` with `download` enabled as a dev-dependency? No need to add a new feature.

2022-06-17 05:48 UTC, bhgomes approved these changes

2022-06-17 12:35 UTC, GhostOfGauss approved these changes

2022-06-17 14:21 UTC, merged