Move `Fp` and `R1CS` to `manta-crypto`
Manta-Network/manta-rs pull request #248
Opened 2022-09-08 22:19 UTC by GhostOfGauss

Moves `Fp` and `R1CS` to `manta-crypto` as part of #40 
---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2022-09-12 19:39 UTC, SupremoUGH approved these changes
Everything seems fine, even though I don't fully understand (de)serialization, so please double check the details of that with Brandon.

2022-09-12 19:39 UTC, SupremoUGH commented on manta-crypto/src/arkworks/codec.rs
> +    fn update<T, F>(&mut self, f: F) -> Option<T>
why do we want this fn to be private?

2022-09-14 09:50 UTC, bhgomes requested changes

2022-09-14 09:50 UTC, bhgomes commented on manta-crypto/src/arkworks/codec.rs
> +//! Codec Utilities
The stuff in this file can go in `arkworks::serialize` instead, we don't need to split this out.

2022-09-14 09:50 UTC, bhgomes commented on manta-crypto/src/arkworks/mod.rs
> +pub mod codec;
Like I mentioned before, we can use `serialize` here instead and do an extension of `ark-serialize` in that module.

2022-09-14 09:50 UTC, bhgomes commented on manta-pay/src/config.rs
> +    constraint::arkworks::{groth16, Boolean, R1CS}, // TODO: Move R1CS with Groth16
fix todo item or leave it out of here (use GH issue to track this)

2022-09-14 09:50 UTC, bhgomes commented on manta-pay/src/crypto/constraint/arkworks/groth16.rs
> +    R1CS, // TODO: Move with Groth16
same as above TODO

2022-09-14 09:50 UTC, bhgomes commented on manta-pay/src/crypto/constraint/arkworks/mod.rs
> +    // TODO: move to constraint with R1CS
same as other TODO

2022-09-14 09:51 UTC, bhgomes requested changes

2022-09-14 09:51 UTC, bhgomes commented on manta-crypto/Cargo.toml
> +    "ark-std",
in this case, cause we need it, lets re-export it too

2022-11-18 20:20 UTC, closed without merging