Feat: upgraded key system
Manta-Network/manta-rs pull request #282
Opened 2022-11-15 12:28 UTC by SupremoUGH

Signed-off-by: Francisco Hernandez Iglesias <f.hernandeziglesias@outlook.com>

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2022-11-15 22:02 UTC, bhgomes requested changes
We need `bip0039` for the signer changes. @AlexParshh please check this PR in the key system

2022-11-16 15:13 UTC, GhostOfGauss approved these changes

2022-11-16 15:13 UTC, GhostOfGauss commented on manta-pay/src/key.rs
> +    bip32::Mnemonic,
Docs still say "BIP39 Mnemonic"

2022-11-16 15:13 UTC, GhostOfGauss commented on manta-pay/src/key.rs
> +    /// Create a new BIP39 mnemonic phrase from the given string.
```suggestion
    /// Create a new BIP32 mnemonic phrase from the given string.
```

2022-11-16 15:13 UTC, GhostOfGauss commented on manta-pay/src/key.rs
> +    fn serialize<S>(mnemonic: &bip32::Mnemonic, serializer: S) -> Result<S::Ok, S::Error>
Docs still say "BIP39 seed"

2022-11-16 18:16 UTC, SupremoUGH commented on manta-pay/src/key.rs
> +#[derivative(Clone(bound = ""), Default(bound = ""))]
Now it's gone because Mnemonic doesn't.

2022-11-17 09:10 UTC, GhostOfGauss submitted a review, later dismissed

2022-11-18 17:17 UTC, GhostOfGauss approved these changes

2022-11-18 20:06 UTC, bhgomes approved these changes

2022-11-18 20:06 UTC, merged