Feat: upgrade asset system
Manta-Network/manta-rs pull request #283
Opened 2022-11-15 20:25 UTC by SupremoUGH

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2022-11-18 19:07 UTC, GhostOfGauss approved these changes

2022-11-18 19:08 UTC, GhostOfGauss commented
@bhgomes do you know why the CI Lint check is skipping?

2022-11-18 20:22 UTC, bhgomes commented
> @bhgomes do you know why the CI Lint check is skipping?

Not really sure why, will have to investigate. Probably it's timing out or overusing resources.

2022-11-18 20:24 UTC, bhgomes requested changes

2022-11-18 20:24 UTC, bhgomes commented on manta-pay/src/simulation/ledger/mod.rs
> +                <Config as transfer::Configuration>::AssetValue,
For all of these kinds of things just make an alias in the `crate::config` file for `AssetId` and `AssetValue` and call them instead.

2022-11-22 15:22 UTC, bhgomes commented on manta-accounting/src/asset.rs
> +impl<I, V, COM> eclair::cmp::PartialEq<Self, COM> for Asset<I, V>
It's currently in flux right now as the ECLAIR derive model is not stabilized.

2022-11-22 15:23 UTC, bhgomes commented on manta-accounting/src/asset.rs
>              .map(move |(id, value)| Asset::new(id, value))
Yes if `collect` is called, they are sorted.

2022-11-22 15:24 UTC, bhgomes commented on manta-accounting/src/asset.rs
>          iter.into_iter().map::<Vec<_>, _>(Into::into).collect()
same

2022-11-22 15:31 UTC, bhgomes commented on manta-accounting/src/asset.rs
> +        fn insert(&mut self, key: Self::Key, asset: Asset<$I, $V>) {
The keys are meant to be unique in the honest system, if you get duplicate keys you can at least handle them in some cases but you can't necessarily handle them in all cases. This is not a protocol error, we are just being defensive here.

2022-11-22 16:57 UTC, bhgomes approved these changes

2022-11-22 17:01 UTC, GhostOfGauss approved these changes

2022-11-22 17:07 UTC, merged