first prototype
Manta-Network/manta-rs pull request #319
Opened 2023-02-15 18:31 UTC by SupremoUGH

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2023-02-17 15:51 UTC, bhgomes requested changes

2023-02-17 15:51 UTC, bhgomes commented on manta-accounting/src/wallet/mod.rs
> +    MissingPAKey,
Just use the full name here.

```suggestion
    MissingProofAuthorizationKey,
```

2023-02-17 15:51 UTC, bhgomes commented on manta-accounting/src/wallet/signer/mod.rs
> +    MissingKey,
```suggestion
    MissingProofAuthorizationKey,
```

2023-02-17 15:51 UTC, bhgomes commented on manta-accounting/src/wallet/signer/mod.rs
> +    MissingKey,
```suggestion
    MissingSpendingKey,
```

2023-02-21 15:51 UTC, bhgomes approved these changes

2023-02-21 15:57 UTC, DanielZhangReal approved these changes

2023-02-21 15:58 UTC, merged