get/set storage exposed to wallet
Manta-Network/manta-rs pull request #328
Opened 2023-03-14 17:33 UTC by SupremoUGH

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2023-03-14 20:16 UTC, Apokalip submitted a review, later dismissed

2023-03-14 20:19 UTC, bhgomes requested changes

2023-03-14 20:19 UTC, bhgomes commented on manta-accounting/src/wallet/signer/mod.rs
> +    }
shouldn't the names be reversed

2023-03-15 11:55 UTC, Apokalip approved these changes

2023-03-15 12:06 UTC, DanielZhangReal approved these changes

2023-03-15 12:26 UTC, bhgomes approved these changes

2023-03-15 12:31 UTC, merged