checkpoint
Manta-Network/manta-rs pull request #329
Opened 2023-03-14 19:28 UTC by SupremoUGH

---

Before we can merge this PR, please make sure that all the following items have been checked off:

- [ ] Linked to an issue with discussion and accepted design OR have an explanation in the PR that describes this work.
- [ ] Added **one** line describing your change in [`CHANGELOG.md`](https://github.com/manta-network/manta-rs/blob/main/CHANGELOG.md) and added the appropriate `changelog` label to the PR.
- [ ] Re-reviewed `Files changed` in the GitHub PR explorer.
- [ ] Checked that changes and commits conform to the standards outlined in [`CONTRIBUTING.md`](https://github.com/manta-network/manta-rs/blob/main/CONTRIBUTING.md).

2023-03-23 20:39 UTC, bhgomes requested changes

2023-03-23 20:39 UTC, bhgomes commented on manta-accounting/src/wallet/mod.rs
> +                    .map_err(Error::SignerConnectionError)?,
you should grab these parameters once outside the loop

2023-03-23 20:39 UTC, bhgomes commented on manta-accounting/src/wallet/signer/mod.rs
> +    pub membership_proof_data: Vec<UtxoAccumulatorWitness<C>>,
Maybe just add a comment here that this is the proof of the latest leaves per tree.

2023-03-23 20:39 UTC, bhgomes commented on manta-crypto/src/accumulator.rs
> +}
This needs a bit more clarification on what it does. And is it really sorting or more grouping?

2023-03-23 20:39 UTC, bhgomes commented on manta-crypto/src/merkle_tree/forest.rs
> +
```suggestion
                for item in items {
                    let tree_index = C::tree_index(&item).into();
                    result[tree_index].push(item);
                }
```

2023-03-28 11:32 UTC, Apokalip approved these changes
lgmt

2023-03-28 17:29 UTC, merged